[package]
name = "buguc"
version = "0.3.0"
edition = "2021"
description = "buguc"
license = " GPL-3.0"
exclude = ["/riscv-gcc"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.10", features = ["derive"] }