[package]
name = "buguc"
version = "0.2.0"
edition = "2021"
description = "buguc"
license = " GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.0"