[package]
name = "buguc"
version = "0.1.0"
edition = "2021"
definitions = "buguc"
license = " GPL"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib-rv32-asm = "0.2.0"
byteorder = "1"